### PR TITLE
Update activesupport

### PR DESCRIPTION
**Pull request by narcisobenigno**
We are trying to use with rails 4.0.0 and its is blocked with this gem. And I update rspec and remove warnings.

### CODE REVIEW

**Comment by rodrigues** [comment]
nice, @njalldev :)

but `activesupport ~> 4` is not so good, `>= 3...` is better to keep old applications ok with `rest_model` :)

would be good to maintain `1.9.2` builds in travis, for the same reason.

thanks!

**Comment by narcisobenigno** [comment]
No problem,

If you think that is better ok (I can change this). But old applications
can use the version 0.2.3. It is hard to mantain olders versions. What
about?

Best

2013/10/3 Victor Rodrigues notifications@github.com

**Comment by rodrigues** [comment]
in the future something can be fixed here and these apps couldn't update it just because they don't use rails 4.. I don't think it's reasonable, since we only depend on activesupport, on things that remain the same.

it's not a huge priority (neither too easy) for many apps upgrading to rails 4, and rest_model shouldn't take this into account.

just pushed these two commits: https://github.com/rodrigues/rest_model/commit/f0efcb6be583ef5d0664eaced21f64cad5c1ad49 , https://github.com/rodrigues/rest_model/commit/713b283b28511bad43e865bd5c2410c0ebe23db7 , to make it `>= 3.2` and `1.9.2` back on travis builds, let's see if they build.

thanks for pushing it forward man! I should need to give some time to rest_model soon :)

**Comment by rodrigues** [comment]
building with 1.9.2 ;)

**Pull request merged**
